# Each new term in the Fibonacci sequence is generated by adding
# the previous two terms. By starting with 1 and 2, the first 10 terms
# will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# Find the sum of all the even-valued terms in the sequence which
# do not exceed four million.
n1 = 1
n2 = 2
s = 0
while n1<4000000:
    if n1%2==0:
        s+=n1
    (n1, n2) = (n2, n1+n2)
print s
